# Generated by Chocoleotey. https://github.com/leobastiani/chocoleotey

$ErrorActionPreference = 'Stop';
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

Install-BinFile -Name 'test_dir' -Path (Join-Path (Join-Path $toolsDir 'bin') 'test_dir.bat')
